@URL = http://localhost:80/user


### 
POST {{URL}}/register
Content-Type: application/json

{
    "name": "user1",
    "password": "password1"
}

###

### 
POST {{URL}}/login
Content-Type: application/json

{
    "name": "user1",
    "password": "password1"
}